# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestChatPrivadoTeste():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_chatPrivadoTeste(self):
    self.driver.get("http://ajudaai.pythonanywhere.com/")
    self.driver.set_window_size(833, 859)
    self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(2) img").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) > td:nth-child(6) img").click()
    self.driver.find_element(By.LINK_TEXT, "Entrar no chat").click()
    self.driver.find_element(By.NAME, "mensagem").click()
    self.driver.find_element(By.NAME, "mensagem").send_keys("Fico no aguardo.")
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(2)").click()
  
